spring.application.name=jenkinpipelnedemo
server.error.whitelabel.enabled=false
spring.servlet.multipart.max-file-size=128KB
spring.servlet.multipart.max-request-size=128KB


spring.datasource.url=jdbc:mysql://host.docker.internal:3306/jpa?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
