spring.application.name=jenkinpipelnedemo
server.error.whitelabel.enabled=false
spring.servlet.multipart.max-file-size=128KB
spring.servlet.multipart.max-request-size=128KB


# Match the database name, username, and password with your docker-compose file
spring.datasource.url=jdbc:mysql://mysql-db:3306/jpa?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
