pipeline {
    agent any

    tools {
        maven 'Maven_3.9'
        jdk 'JDK_17'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/pjpaparao/springboot.git'
            }
        }

        stage('Build') {
            steps {
                dir('jenkinpipelnedemo') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('jenkinpipelnedemo') {
                    bat 'mvn test'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('jenkinpipelnedemo') {
                    bat 'docker-compose down'
                    bat 'docker-compose up -d --build'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
