pipeline {
    agent any

    tools {
        maven 'Maven_3.9'   // configure Maven in Jenkins global tools
        jdk 'JDK_17'        // configure JDK in Jenkins global tools
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/pjpaparao/springboot.git'
            }
        }

stage('Build') {
    steps {
        dir('jenkinpipelnedemo') {
            bat 'mvn clean package'
        }
    }
}

stage('Test') {
    steps {
        dir('jenkinpipelnedemo') {
            bat 'mvn test'
        }
    }


stage('Deploy') {
    steps {
        dir('jenkinpipelnedemo') {
            bat 'docker network create springboot-net || exit 0'
            bat 'docker volume create mysql-data || exit 0'
            bat '''
            docker ps -a --format "{{.Names}}" | findstr /x "mysql-db" >nul
            if errorlevel 1 (
                docker run -d --name mysql-db --network springboot-net -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=mydb -p 3306:3306 -v mysql-data:/var/lib/mysql mysql:8
            ) else (
                echo mysql-db already exists, skipping creation
            )
            '''
            bat 'docker build -t springboot-app .'
            bat 'docker rm -f springboot-app-container || exit 0'
            bat 'docker run -d --name springboot-app-container --network springboot-net -p 8080:8080 springboot-app'
        }
    }
}
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
